### ISSUE TITLE
Questions about Update the model weight and config files 

### ISSUE THREAD

**Issue by 3A732038** [rinnakk/prefix-tuning-gpt#1]
Excuse me, when I use this prefix-tuning-gpt model, it can be executed.

But by 2023/3/20, I found that the Hugging Face website said that there was an updated model, which caused a warning to appear when I ran this code (as shown below) You are using a model of type gpt_neox to instantiate a model of type gpt-neox. This is not supported for all configurations of models and can yield errors.

I would like to ask if there is any way to solve it?

`base_model = GPTNeoXForCausalLM.from_pretrained(config.pretrained_model_dir)`

**Comment by ZHAOTING** [comment]
Hi @3A732038 , I have commited a new commit https://github.com/rinnakk/prefix-tuning-gpt/commit/bd6027bf206ddc439b6b542cc7ff094ccfeb7d29 to make the code work with the updated model from Huggingface Model Hub. Please check the update log.

**Comment by ZHAOTING** [comment]
Good point! 
You are right. It is a legacy from the previous version of the gpt-neox modeling code.
Since the huggingface implementation of gpt-neox does not support explicitly providing position ids as inputs, you can safely remove the position ids from model inputs to get rid of the warning.

**Comment by 3A732038** [comment]
Thank you for your reply, I still have two questions:

1. I looked at your model structure, and it seems that there is no layer that focuses on location information, so I would like to ask where the information that considers location is placed in the model?

2. In addition, I would like to ask, if I want to change my pre-training model from gpt-neox to gpt, should I change this program
`GPTNeoXForCausalLM.from_pretrained('rinna/japanese-gpt-neox-small')`
replace with
`GPT2LMHeadModel.from_pretrained('gpt2')`
Then the tokenizer must also be switched to the corresponding tokenizer of the gpt2 model
In this way, the problem of model mismatch will not occur, and the training effect will be better?

**Comment by ZHAOTING** [comment]
1. In gpt2, position embedding (called `wpe`) encodes location information. In gpt-neox, rotary embedding (search for keyword `rotary`) encodes it.
2. You should change both the model class/name and tokenizer class/name. However, if you use `AutoModelForCausalLM` and `AutoTokenizer`, you can change only the model name and tokenizer name. For example
    ~~~
    model = AutoModelForCausalLM.from_pretrained("gpt2")
    tokenizer = AutoTokenizer.from_pretrained("gpt2")
    ~~~

**Comment by 3A732038** [comment]
So if I use AutoModelForCausalLM and AutoTokenizer can I use prefix_tuning directly?
Or the internal structure of the model needs to be changed.
